---
- hosts: all

  vars_prompt:
    name: CONFIRM
    prompt: "\n\n\nDo you want to install and configure chrome (yes/no)?"
    default: "yes"
    private: no

  pre_tasks:

    - name: Cancel on no confirmation
      meta: end_play
      when: not ( (CONFIRM | lower) == "y" or (CONFIRM | lower) == "yes" )

  tasks:

    - name: Download chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp

    - name: Install chrome
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb

    - name: Create policy folders
      become: true
      file:
        path: /etc/opt/chrome/policies/recommended/
        recurse: yes
        state: directory

    - name: Configure default settings
      become: true
      copy:
        dest: /etc/opt/chrome/policies/recommended/policies.json
        src: ./roles/chrome/recommended-policies.json # TODO https://chromeenterprise.google/policies/#ExtensionInstallForcelist
