---
- hosts: all

  vars_prompt:
    name: CONFIRM
    prompt: "\n\n\nDo you want to install and configure chrome (yes/no)?"
    default: "yes"
    private: no

  pre_tasks:

    - name: Cancel on no confirmation
      meta: end_play
      when: not ( (CONFIRM | lower) == "y" or (CONFIRM | lower) == "yes" )

  tasks:

    # Installation
    - name: Add google key
      become: true
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub

    - name: Add chrome repository
      become: true
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        filename: chrome

    - name: Install chrome
      become: true
      apt:
        name: google-chrome-stable

    # Configuration
    - name: Create policy folders
      become: true
      file:
        path: /etc/opt/chrome/policies/recommended/
        recurse: yes
        state: directory

    - name: Configure default settings
      become: true
      copy:
        dest: /etc/opt/chrome/policies/recommended/policies.json
        src: ./roles/chrome/recommended-policies.json # TODO https://chromeenterprise.google/policies/#ExtensionInstallForcelist
