---
- import_playbook: upgrade-packages.yml
- import_playbook: display.yml
- import_playbook: passwordless-sudo.yml
- import_playbook: terminal.yml
- import_playbook: gnome.yml
- import_playbook: firefox.yml
- import_playbook: chrome.yml
