---
- hosts: all

  vars:
    PANEL_SIZE_MIN: 12
    PANEL_SIZE_MAX: 128

  vars_prompt:
    name: PANEL_SIZE
    prompt: "\n\n\nWhat panel size would you like ({{ PANEL_SIZE_MIN }}-{{ PANEL_SIZE_MAX }})?"
    default: 32
    private: no

  pre_tasks:

    - name: Halt on invalid panel size
      fail:
        msg: >-
          Invalid panel size! Configuration halted!
      when: not ( (PANEL_SIZE | int) >= PANEL_SIZE_MIN and (PANEL_SIZE | int) <= PANEL_SIZE_MAX )

  tasks:

    - name: Install GNOME Tweak Tool
      become: true
      apt:
        name: gnome-tweak-tool
        #update_cache: true # Shouldn't be needed due to 'Update and upgrade packages'

    # TODO
      # Install Alt-Tab Switcher Popup Delay Removal
      # Install TopIcons Plus
      # Desktop Icons NG (DING)

    # Dash to Panel
    - name: Install Dash to Panel Extension (GNOME)
      become: true
      apt:
        name: gnome-shell-extension-dash-to-panel
        #update_cache: true # Shouldn't be needed due to 'Update and upgrade packages'

    - name: Configure panel size
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-size"
        value: "32"

    - name: Enable app hotkeys
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/hot-keys"
        value: "true"

    - name: Disable app hotkey number overlay
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/hotkeys-overlay-combo"
        value: "'NEVER'"

    # Inconveniences
    - name: Disable middle click to paste
      dconf:
        key: "/org/gnome/desktop/interface/gtk-enable-primary-paste"
        value: "false"

    # Icon Bar
    - name: Enable display of pattery percentage
      dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"

    - name: Enable weekday on clock
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"

    - name: Enable week numbers on calendar
      dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: "true"

    # Workspaces
    - name: Disable dynamic workspaces
      dconf:
        key: "/org/gnome/mutter/dynamic-workspaces"
        value: "false"

    - name: Set static workspaces to 1
      dconf:
        key: "/org/gnome/desktop/wm/preferences/num-workspaces"
        value: "1"

    # Files (nautilus)
    - name: Set the file view
      dconf:
        key: "/org/gnome/nautilus/preferences/default-folder-viewer"
        value: "'list-view'"

    - name: Set the file details columns
      dconf:
        key: "/org/gnome/nautilus/list-view/default-visible-columns"
        value: "['name', 'size', 'owner', 'permissions', 'date_modified']"

    # Locale
    - name: Set the locale to english
      dconf:
        key: "/system/locale/region"
        value: "'en_GB.UTF-8'"
