---
- hosts: all

  vars_prompt:
    name: CONFIRM
    prompt: "\n\n\nDo you want to enable passwordless sudo (yes/no)?"
    default: "yes"
    private: no

  pre_tasks:

    - name: Cancel on no confirmation
      meta: end_play
      when: not ( (CONFIRM | lower) == "y" or (CONFIRM | lower) == "yes" )

  tasks:

    # https://stackoverflow.com/a/33362805/4255176
    - name: Enable passwordless sudo for sudo:ers
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "%sudo ALL=(ALL) NOPASSWD: ALL # Enable passwardless sudo for sudo:ers"
        validate: visudo -cf %s
